//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SesionTrabajo
    {
        public int IdSesion { get; set; }
        public string Tareas { get; set; }
        public decimal PrecioHora { get; set; }
        public int IdProyecto { get; set; }
        public int CantTareas { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public bool Activo { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
    }
}
